# Example LSTM Configuration for DeepHit Model
# This configuration uses LSTM networks for competing risks analysis

# Model type to use
model_type: "deephit"  # Options: "deepsurv", "deephit"

# For DeepHit, we model all competing risks (no target_endpoint filtering)
# target_endpoint: null  # Model all event types

# Network architecture configuration
network:
  # Network type: LSTM for temporal sequence modeling
  type: "lstm"  # Options: "ann" (default MLP), "lstm"
  
  # LSTM specific parameters
  lstm:
    hidden_dim: 128       # Larger hidden dimension for competing risks
    num_layers: 2         # Number of LSTM layers
    bidirectional: true   # Use bidirectional LSTM
    sequence_length: 7    # Longer sequences for complex temporal patterns
  
  # DeepHit specific parameters
  deephit:
    alpha: 0.3            # Loss weighting parameter
    sigma: 0.2            # Ranking loss parameter
    time_grid: [365, 730, 1095, 1460, 1825]  # 1, 2, 3, 4, 5 years

# Hyperparameter search space for optimization
search_space:
  # Common parameters for all models
  common:
    learning_rate:
      type: "float"
      min: 0.0001
      max: 0.005      # Lower max for DeepHit stability
      log: true
    dropout:
      type: "float"
      min: 0.1
      max: 0.6        # Higher dropout for regularization
    optimizer:
      type: "categorical"
      values: ["Adam", "AdamW"]
    batch_size:
      type: "categorical"
      values: [32, 64, 128]  # Smaller batches for LSTM DeepHit
  
  # LSTM specific search space
  lstm:
    sequence:
      type: "int"
      min: 5
      max: 10       # Longer sequences for competing risks
    lstm_hidden_dim:
      type: "int"
      min: 64
      max: 128      # Larger hidden dimensions
    lstm_num_layers:
      type: "int"
      min: 1
      max: 3
    bidirectional:
      type: "categorical"
      values: [true, false]
  
  # DeepHit specific search space
  deephit:
    alpha:
      type: "float"
      min: 0.1
      max: 0.8        # Broader range for LSTM
    sigma:
      type: "float"
      min: 0.1
      max: 0.5

# Optimization settings
optimization:
  n_trials: 25          # Reduced for LSTM DeepHit (slower training)
  patience: 7           # Higher patience for complex model
  seed: 42
  metric: "loglik"      # Optimize log-likelihood

# Class imbalance handling
balance:
  enable: false         # Disable for competing risks
  method: "near_miss"
  sampling_strategy: "majority"
  near_miss_version: 1

# Evaluation settings
evaluation:
  dca:
    enable: true
    horizons: [365, 730, 1095, 1460, 1825]
    threshold_grid:
      start: 0.01
      stop: 0.40      # Lower max threshold for competing risks
      num: 40
    ipcw: true