model_type: deephit
target_endpoint: null
network:
  type: ann
  default:
    hidden_dims:
    - 128
    - 64
    - 32
    num_layers: 3
    dropout: 0.2
    batch_size: 64
    learning_rate: 0.001
    epochs: 100
  lstm:
    hidden_dims:
    - 128
    - 64
    - 32
    num_layers: 2
    bidirectional: true
    sequence_length: 5
  deephit:
    alpha: 0.2
    sigma: 0.1
    time_grid:
    - 365
    - 730
    - 1095
    - 1460
    - 1825
search_space:
  common:
    learning_rate:
      type: float
      min: 0.0001
      max: 0.01
      log: true
    num_layers:
      type: int
      min: 2
      max: 4
    hidden_units_layer1:
      type: int
      min: 16
      max: 128
    hidden_units_layer2:
      type: int
      min: 16
      max: 128
    hidden_units_layer3:
      type: int
      min: 8
      max: 64
    hidden_units_layer4:
      type: int
      min: 4
      max: 32
    dropout:
      type: float
      min: 0.0
      max: 0.8
    optimizer:
      type: categorical
      values:
      - Adam
      - AdamW
    batch_size:
      type: categorical
      values:
      - 64
      - 128
      - 256
      - 512
      - 1024
  lstm:
    sequence:
      type: int
      min: 3
      max: 10
    lstm_hidden_dim:
      type: int
      min: 32
      max: 128
    lstm_hidden_dim_layer1:
      type: int
      min: 64
      max: 128
    lstm_hidden_dim_layer2:
      type: int
      min: 32
      max: 96
    lstm_hidden_dim_layer3:
      type: int
      min: 16
      max: 64
    lstm_num_layers:
      type: int
      min: 1
      max: 3
    bidirectional:
      type: categorical
      values:
      - true
      - false
  deephit:
    alpha:
      type: float
      min: 0.1
      max: 1.0
    sigma:
      type: float
      min: 0.1
      max: 1.0
optimization:
  n_trials: 2
  patience: 3
  seed: 42
  metric: loglik
balance:
  enable: false
  method: near_miss
  sampling_strategy: majority
  near_miss_version: 3
evaluation:
  dca:
    enable: true
    horizons:
    - 365
    - 730
    - 1095
    - 1460
    - 1825
    threshold_grid:
      start: 0.01
      stop: 0.5
      num: 50
    ipcw: true
